export const ACTION_SET_REPORTS = 'reports/ACTION_SET_REPORTS'
export const ACTION_ADD_REPORT = 'reports/ACTION_ADD_REPORT'
export const ACTION_DELETE_REPORT = 'reports/ACTION_DELETE_REPORT'
export const ACTION_UPDATE_REPORT = 'reports/ACTION_UPDATE_REPORT'

export const MUTATION_SET_REPORTS = 'reports/MUTATION_SET_REPORTS'
export const MUTATION_ADD_REPORT = 'reports/MUTATION_ADD_REPORT'
export const MUTATION_DELETE_REPORT = 'reports/MUTATION_DELETE_REPORT'
export const MUTATION_UPDATE_REPORT = 'reports/MUTATION_UPDATE_REPORT'

export const GETTER_REPORT = 'reports/GETTER_USER'
